### ISSUE TITLE
$200 for Google Assistant Activation

### ISSUE THREAD

**Issue by mentalisttraceur** [adolfintel/OpenPods#101]
Offering $200 (that's US dollars) over PayPal to whoever implements a way to activate Google Assistant from the AirPods Pro, to be paid once the feature makes its way into a new F-Droid release of this OpenPods app and I have confirmed that it is working.

If the solution works but for some reason the maintainer of this app does not want to merge and release it, I'll still consider paying some or all of that. But I want everyone to play nice and I don't want to encourage hostile forks or anything like that.

I will consider other methods besides PayPal, but no promises so if you can't receive it over PayPal, ask me ahead of time or work something out with an intermediary can take PayPal payments ahead of time.

If multiple people put in work to make it happen I make no promises about how much of the money will go to who, but I will make an effort to split it up in a way that seems fair.

**The more time passes the less guaranteed my ability or desire to pay this becomes, so the sooner you act, the better** (and if this message is old by the time you see it, ask me if you want to be sure I still stand by).

I encourage others who want this figured out (and made available openly so that the open source world can benefit from it) and who are willing to pay for it to comment below with how much you are willing to chip in in addition to my offer. I also encourage anyone who has permissions to edit this issue's title to update the amount in the title to reflect the combined total of all bounties offered.

**Comment by mentalisttraceur** [comment]
I presume #58 is relevant here, and this is going to require reverse-engineering of how the AirPods communicate, because I suspect that the work required to achieve Google Assistant activation will also pave the way for all of the other controls and click rebinding and so forth.

**Comment by adolfintel** [comment]
I'll leave this open in case someone wants to do it

**Comment by mentalisttraceur** [comment]
Another $50 if I can activate or deactivate speech-to-text from the AirPods Pro the same way that you can by pressing microphone button on the top right of Gboard.

In fact same in the reverse: if you just get the speech to text activation working, but not Google Assistant activation, then $200 for that.

I think it's pretty obvious by now that these bounty amounts are largely whimsical on my part, and are entirely based on the assumption that most of the reverse engineering work once figured out for one thing will readily enable the other.

**Comment by moboch** [comment]
https://play.google.com/store/apps/details?id=com.dotarrow.assistantTrigger Just wanted to leave this here because this app can apparently do just that, it's not open source, though. I don't have any Airpods to try but maybe you could give it a try. My decision whether to buy Airpods pro is basically dependent on this feature working so it would be great if you could report how it goes!

**Comment by mentalisttraceur** [comment]
@moboch Thank you, but I won't be checking that app out - my willingness to spend money on open source development vastly exceeds my willingness to spend money on someone's closed source app. For what it's worth nowadays I use the latest Pixel Buds with my Android phone, and it's working really well. (Bounty offer remains open for now despite that, but I actually might shrink it or revoke it soon.)

**Comment by manindertaggar** [comment]
Is the reward still on? I have implemented the code in my fork??

**Comment by mentalisttraceur** [comment]
@manindertaggar Yes.

**Comment by fvasco** [comment]
@mentalisttraceur you should post a bounty for this feature

https://www.bountysource.com/

**Comment by mentalisttraceur** [comment]
This seems to be no longer needed. "Hey Google" phrases and speech-to-text seem to just work out-of-the-box now on my Pixel 4 with my Airpods Pro. So I'm closing this specific issue for now.

I may still be interested in paying bounties for open source work towards making Airpods more usable or featureful on Android, the same conditions apply, in particular

> to be paid once the feature makes its way into a new F-Droid release of this OpenPods app and I have confirmed that it is working

unless there is good reason for making an exception.

**Comment by maksim-pinguin** [comment]
> This seems to be no longer needed. "Hey Google" phrases and speech-to-text seem to just work out-of-the-box now on my Pixel 4 with my Airpods Pro. So I'm closing this specific issue for now.

I can't confirm "hey Google" working out-of-the-box or elsewise. But I'm using a Xiaomi Poco f2 Pro. Knowing that Xiaomi's Custom ROM is making trouble with background processes I turned of all optimization for openpods and Google assistant. Still no luck. 

In my experience 'Hey Google' still only works with the mic of my phone not with the airpod's mic. So calling Google assistant with the phone in my bag/pocket never works.

**Comment by moboch** [comment]
> > This seems to be no longer needed. "Hey Google" phrases and speech-to-text seem to just work out-of-the-box now on my Pixel 4 with my Airpods Pro. So I'm closing this specific issue for now.
> 
> I can't confirm "hey Google" working out-of-the-box or elsewise. But I'm using a Xiaomi Poco f2 Pro. Knowing that Xiaomi's Custom ROM is making trouble with background processes I turned of all optimization for openpods and Google assistant. Still no luck.
> 
> In my experience 'Hey Google' still only works with the mic of my phone not with the airpod's mic. So calling Google assistant with the phone in my bag/pocket never works.

 I get the same behavior, "hey google" only works with the phone's mic.

**Comment by mentalisttraceur** [comment]
I think you guys are right. I think I just got the impression that it was working through my AirPods because my phone was close enough to hear me at the time.

So I might reopen this. Have to do some more testing to see how well it works as-is in a few situations.

**Comment by maksim-pinguin** [comment]
> Is the reward still on? I have implemented the code in my local.

Any updates on that?

**Comment by kavishdevar** [comment]
Is the bounty still open for other development (like ear detection, conversational awareness, accurate battery information, etc.), not just voice assistant (might be able to get that working too, though, via button long presses)?

**Comment by mentalisttraceur** [comment]
@kavishdevar Not for now, sorry.

In fact, I'm now temporarily closing the bounty for the original assistant feature request as well.

Feel free to ask me again in about a year.
